---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
        #- name: instance_debian
        #image: docker.io/amd64/debian:latest
        #pre_build_image: true

    - name: instance_buster
      image: docker.io/buster:latest
      pre_build_image: true
      command: /sbin/init
      tmpfs:
        - /run
        - /tmp
      capabilities:
      - SYS_ADMIN
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
verifier:
  name: ansible
