---
# tasks file for installTsmClient
- name: Extrae los deb en el tmp
  ansible.builtin.unarchive:
    src: 8.1.6.1-TIV-TSMBAC-LinuxX86_DEB.tar.gz
    dest: /tmp

- name: Instala todos los deb
  apt:
    deb: "{{ item }}"
  loop:
    - /tmp/8.1.6.1-TIV-TSMBAC-LinuxX86_DEB/gskcrypt64_8.0-55.2.linux.x86_64.deb
    - /tmp/8.1.6.1-TIV-TSMBAC-LinuxX86_DEB/gskssl64_8.0-55.2.linux.x86_64.deb
    - /tmp/8.1.6.1-TIV-TSMBAC-LinuxX86_DEB/tivsm-api64.amd64.deb
    - /tmp/8.1.6.1-TIV-TSMBAC-LinuxX86_DEB/tivsm-apicit.amd64.deb
    - /tmp/8.1.6.1-TIV-TSMBAC-LinuxX86_DEB/tivsm-ba.amd64.deb
    - /tmp/8.1.6.1-TIV-TSMBAC-LinuxX86_DEB/tivsm-bacit.amd64.deb

- name: Generando los Linkeos
  ansible.builtin.file: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}" 
    state: link 
  loop:
    - { src: /usr/local/ibm/gsk8_64/lib64/libgsk8ssl_64.so, dest: /usr/lib/libgsk8ssl_64.so }
    - { src: /usr/local/ibm/gsk8_64/lib64/libgsk8iccs_64.so, dest: /usr/lib/libgsk8iccs_64.so }
    - { src: /usr/local/ibm/gsk8_64/lib64/libgsk8cms_64.so, dest: /usr/lib/libgsk8cms_64.so }
    - { src: /usr/local/ibm/gsk8_64/lib64/libgsk8sys_64.so, dest: /usr/lib/libgsk8sys_64.so}
    - { src: /usr/local/ibm/gsk8_64/lib64/libgsk8km_64.so, dest: /usr/lib/libgsk8km_64.so }
    - { src: /opt/tivoli/tsm/client/ba/bin/EN_US, dest: /opt/tivoli/tsm/client/ba/bin/ES_AR }

- name: Copiando servicio 
  ansible.builtin.copy:
    src: /opt/tivoli/tsm/client/ba/bin/dsmcad.service
    dest: /etc/systemd/system/dsmcad.service
  notify: Restart dsmcad
  
