---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: docker.io/pycontribs/debian
    pre_build_image: true
    capabilities:
    - SYS_ADMIN

  #- name: instance_ubuntu
  #  image: docker.io/pycontribs/ubuntu:latest
   # pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
